name: flutter_amplify_login
description: An example Flutter app using Very Good CLI and AWS Amplify Authentication
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  auth_client:
    path: packages/auth_client
  user_repository:
    path: packages/user_repository
  form_inputs:
    path: packages/form_inputs
  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
